name: CS605_Qwen_PAT_Shared
on: [push, workflow_dispatch]

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: bash ./run.sh
      - name: Reminder
        run: |
          echo "Reminder to practice version control as a collaborator in this repository"
          echo "This should run the main.py file"
